---
title: "Read Me"
author: "Vishal and Blake"
date: "July 21, 2016"
output: 
  html_document:
    keep_md:  true
---

### **Purpose**    
Chulwahlar is part of the island group Urbano. Chulwahlar exports flower plants that bloom in winter. Prime Minister of Chulwahlar wants to forecast the exports for the upcoming season in 2014 using the past exports data.  

**For a detailed executive summary, please open "Executive Summary.docx" in "Paper" directory.**    


### Data  
we have following data sets available :  
  * CSV file that contains As-is or observed data for the 3 plants - Efak, Wuge, Etel 
  * CSV file that contains planned data -desired results  
  * CSV file that contains indicators influencing data
  
### **Directory Structure**  
Following is the directory structure for this project:  
  
             Root --> README.md
              |
              |------> Load  
              | 
              |------> Data  
              |
              |------> Analysis      
              |
              |------> Paper      
              
  
* Step 1 : Please click on "Load/ChulwahlarForecast.md" to load data and convert the data into a timeseries.  
* Step 2 : Please click on "Analysis/AnalysisandForecast.md" file for further insights for forecasts.  
* Step 3 : Evaluation of different ForecastModels is done at "Analysis/ForecastingModels.md".  
* Step 4 : Go to "Paper" folder and click on "Summary.md" to identify best model. Also open "Executive Summary.docx" file for detailed summary on forecast.

